language: node_js
sudo: false
node_js:
  - "5.0"
env:
  global:
    - SDK=latest
  matrix:
    - CORE=snes9x-next
    - CORE=vba-next
    - CORE=gambatte
    - CORE=nestopia
    - CORE=picodrive
    - CORE=stella
    - CORE=gw
    - CORE=vecx
git:
  submodules: false
before_script:
  - |
    CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - |
    wget -qO- https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz | tar xvz
    ./emsdk_portable/emsdk update
    ./emsdk_portable/emsdk install $SDK
    ./emsdk_portable/emsdk activate $SDK
    source ./emsdk_portable/emsdk_env.sh
before_install:
  - git submodule update --init core/$CORE
script:
  - npm run build -- core/$CORE
  - npm test -- -g $CORE
cache:
  bundler: true
  directories:
    - node_modules
    - jspm_packages
    - emsdk_portable
