language: node_js
sudo: false
node_js:
  - "5.0"
env:
  global:
    - SDK=sdk-1.34.1-64bit
  matrix:
    - CORE=snes9x-next
    - CORE=vba-next
    - CORE=gambatte
    - CORE=nestopia
    - CORE=picodrive
    - CORE=stella
    - CORE=gw
    - CORE=vecx
git:
  submodules: false
before_script:
  - |
    wget -qO- https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz | tar xvz
    cd emsdk_portable
    ./emsdk update
    ./emsdk install $SDK
    ./emsdk activate $SDK
    source ./emsdk_env.sh
before_install:
  - git submodule update --init core/$CORE
script:
  - npm run build -- core/$CORE
  - npm test -- -g $CORE
cache:
  bundler: true
  directories:
    - node_modules
    - jspm_packages
    - emsdk_portable
