language: node_js
sudo: false
before_install:
  - git clone https://github.com/urho3d/emscripten-sdk.git emsdk_portable
  - (cd emsdk_portable && source ./emsdk_env.sh)
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4"
script:
  - npm run build
