language: node_js
sudo: false
node_js:
  - "5.0"
env:
  global:
    - SDK=latest
  matrix:
    - CORE=snes9x-next
    - CORE=vba-next
    - CORE=gambatte
    - CORE=nestopia
    - CORE=picodrive
    - CORE=stella
    - CORE=gw
    - CORE=vecx
git:
  submodules: false
addons:
  apt:
    sources:
      - kubuntu-backports
    packages:
      - cmake
      - clang
before_script:
  - |
    git clone https://github.com/juj/emsdk.git
    cd emsdk
    ./emsdk update
    ./emsdk install $SDK
    ./emsdk activate $SDK
    source ./emsdk_env.sh
before_install:
  - git submodule update --init core/$CORE
script:
  - npm run build -- core/$CORE
  - npm test -- -g $CORE
cache:
  bundler: true
  directories:
    - node_modules
    - jspm_packages
    - emsdk
    - cmake-2.8.11
    - cmake
