language: node_js
sudo: false
before_install:
  - git clone https://github.com/urho3d/emscripten-sdk.git emsdk_portable
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4"
script:
  - cd emsdk_portable
  - source ./emsdk_env.sh
  - cd ..
  - npm run build
